import type { QuestDefinition } from "./types";

export const QUEST_DEFINITIONS: QuestDefinition[] = [
  {
    id: "first-pin",
    title: "Drop Your First Pin",
    description: "Mark a spot on Emory Campus and share it with others.",
    category: "social",
    difficulty: "easy",
    icon: "📍",
    objectives: [
      {
        id: "pins",
        description: "Drop a pin on the map",
        target: 1,
        unit: "pins",
      },
    ],
    reward: { xp: 75, label: "75 XP" },
    collectible: true,
  },
  {
    id: "first-steps",
    title: "First Steps",
    description: "Take your first steps and uncover a piece of Emory Campus.",
    category: "exploration",
    difficulty: "easy",
    icon: "👣",
    objectives: [
      {
        id: "tiles",
        description: "Explore a tile on Emory Campus",
        target: 1,
        unit: "tiles",
      },
    ],
    reward: {
      xp: 50,
      label: "50 XP",
    },
    collectible: true,
  },
  {
    id: "woodruff-visit",
    title: "Hit the Gym",
    description: "Make your way to the Woodruff PE Center.",
    lore: "Every explorer needs a base. Yours has a climbing wall.",
    category: "exploration",
    difficulty: "easy",
    icon: "🏋️",
    objectives: [
      {
        id: "location",
        description: "Visit Woodruff PE Center",
        target: 1,
        unit: "visit",
      },
    ],
    reward: { xp: 100, label: "100 XP" },
    collectible: true,
    location: { lat: 33.793311, lng: -84.325104, radiusM: 150 },
  },
  {
    id: "white-hall-visit",
    title: "Lecture Hall Legend",
    description: "Find your way to White Hall.",
    lore: "Many have sat in these seats. Few have truly been present.",
    category: "exploration",
    difficulty: "easy",
    icon: "🎓",
    objectives: [
      {
        id: "location",
        description: "Visit White Hall",
        target: 1,
        unit: "visit",
      },
    ],
    reward: { xp: 100, label: "100 XP" },
    collectible: true,
    location: { lat: 33.790755, lng: -84.325904, radiusM: 80 },
  },
  {
    id: "msc-visit",
    title: "Science Side of Campus",
    description: "Check out the Math and Science Center.",
    lore: "All the best discoveries happen here. Or so they claim.",
    category: "exploration",
    difficulty: "easy",
    icon: "🔬",
    objectives: [
      {
        id: "location",
        description: "Visit Math and Science Center",
        target: 1,
        unit: "visit",
      },
    ],
    reward: { xp: 100, label: "100 XP" },
    collectible: true,
    location: { lat: 33.790170, lng: -84.326702, radiusM: 100 },
  },
  {
    id: "emory-scout",
    title: "Emory Scout",
    description: "Explore Emory Campus and reveal what lies beyond the fog.",
    lore: "The ancient cartographers say: a map unwalked is a map unfinished.",
    category: "exploration",
    difficulty: "easy",
    icon: "🗺️",
    objectives: [
      {
        id: "tiles",
        description: "Explore tiles on Emory Campus",
        target: 10,
        unit: "tiles",
      },
    ],
    reward: {
      xp: 250,
      label: "250 XP",
    },
    collectible: true,
  },
];
